---

- name: Install LDAP packages.
  dnf: name="{{item}}"
  with_items:
  - openldap
  - openldap-servers
  - openldap-clients

- name: Start and enable server.
  service:
    name: slapd
    state: started 
    enabled: yes

- name: Set ldap config directory ownership.
  file:
    path: /etc/openldap/
    state: directory
    recurse: yes
    owner: ldap
    group: ldap
  notify:
  - restart openldap

- name: Place ldap config.
  template:
    #src: ldap.conf.j2
    #dest: /etc/openldap/ldap.conf
    src: slapd.conf.j2
    dest: /etc/openldap/slapd.conf
    mode: 0644
    owner: ldap
    group: ldap
    seuser: _default
    setype: _default
    serole: _default
    selevel: _default
  notify: 
  - restart openldap

- name: Delete old config dir.
  file:
    path: /etc/openldap/slapd.d/
    state: absent

- name: Create data directory.
  file:
    path: /var/lib/openldap-data
    state: directory
    owner: ldap
    group: ldap
    seuser: _default
    setype: _default
    serole: _default
    selevel: _default
  notify:
  - restart openldap

- meta: flush_handlers

- name: Place example data.
  import_tasks: example.yml
